package com.instarsocial.parquet;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;

import java.io.File;
import java.io.FileInputStream;
import java.nio.charset.StandardCharsets;
import static org.junit.Assert.*;

/**
 * Tests for {@link App} using the Arrange-Act-Assert pattern.
 */

public class AppTest {

    /** Temporary file generated by the test. */
    private static File generatedFile;

    @BeforeClass
    public static void beforeAll() {
        generatedFile = null;
    }

    @AfterClass
    public static void afterAll() {
        if (generatedFile != null && generatedFile.exists()) {
            generatedFile.delete();
        }
    }

    @Test
    public void Should_CreateParquetFile_When_CallingGenerateParquetFileFor() throws Exception {
        // Arrange
        DateTime dateTime = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeZone.UTC);

        // Act
        org.apache.hadoop.fs.Path actual = App.generateParquetFileFor(dateTime);

        // Assert
        assertNotNull("Path should not be null", actual);
        generatedFile = new File(actual.toString());
        assertTrue("Generated file should exist", generatedFile.exists());

        try (FileInputStream fis = new FileInputStream(generatedFile)) {
            byte[] magic = new byte[4];
            int read = fis.read(magic);
            assertEquals(4, read);
            assertEquals("PAR1", new String(magic, StandardCharsets.US_ASCII));
        }
    }
}
